### ISSUE TITLE
[Request] Can you make it compatible with gamepad?

### ISSUE THREAD

**Issue by xatornet** [iArtorias/elden_pause#1]
As the title says, what about doing it so that, for instance, doing some START+SELECT or something like that, it works with gamepad?

It's just a little suggestion. Thanks for everything and great work!!

**Comment by iArtorias** [comment]
Hi, it's likely possible to implement. I will take a look in the next few days.

**Comment by Arthursza** [comment]
if you use dualshocks, its easy to map something like top touchpad press to the P letter in ds4win. theres also joytokey

implemantation of a default gamepad key for pause may be troublesome, theres no standards for xinput/dinput, and a shortcut that would work for a controller brand may not work with another. but if you feel like going that way, l3+r3 would be a safer bet.

by the way, thank you for the release of this mod

**Comment by iArtorias** [comment]
This game works perfectly fine with DS4Windows by emulating the Xbox controller. I will probably come with the controller solution later today, stay tuned.

**Comment by iArtorias** [comment]
The Xinput controllers has just been added (DS4Windows also works fine with DS4 controller). Enjoy.
