### ISSUE TITLE
real pause

### ISSUE THREAD

**Issue by Arthursza** [iArtorias/elden_pause#2]
is it possible to suspend gpu/cpu usage in paused mode? your method is perfect regarding gameplay, no annoying fast forward, but game still renders and consumes resources unnecessarily.

i wonder thats why they dont have it build ingame, maybe is it being a technical challenge to big for the studio that they opted for the philosophy excuse of the souls franchise...

**Comment by techiew** [comment]
This is not feasible, you'd end up pausing the game completely and you'd have the same behavior as my mod, or if you somehow skip the game's main render loop you'd break the game menu which is the great thing about this mod.

**Comment by iArtorias** [comment]
My mod patches the binary to force usage of the internal pause flag. If you're looking for the "real" pause alternative, go for 
@techiew solution.

**Comment by Arthursza** [comment]
thank you both anyway. i wonder if i can use both mods, being able to choose when i want to pause to use the menu, and when i want to be a few minutes afk to give my vintage setup that poorly run this game a little break to cool down.
