### ISSUE TITLE
Add a window focus toggle

### ISSUE THREAD

**Issue by fefo-dev** [iArtorias/elden_pause#4]
The pause key (either on keyboard or controller) works globally and will toggle pause without window focus -  just typing now I've paused and unpaused the game multiple times.

Please add a way for it to work only when the game window is focused (maybe by default) and a toggle if you find the present behavior useful.

Thanks.

**Comment by iArtorias** [comment]
This is actually a good idea, I will think about the possible solution. Thanks.

**Comment by iArtorias** [comment]
Added that feature (thanks to [X-rays5](https://github.com/X-rays5)).
